# SAM template for CodeBuild
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: A simple AWS Lambda for retrieving information from the RecordsDynamnoDB table.
Resources:
  GetRecordsFx:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/get_records_fx-1.0-SNAPSHOT.jar
      Handler: com.revature.get_records.GetRecordsHandler
      Runtime: java8.al2
      Description: Java function
      MemorySize: 256
      Timeout: 30
      Tracing: Active
      Policies:
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
